[package]
name = "rustblock"
version = "0.1.0"
authors = ["Peter Lyons <pete@peterlyons.com>"]

[dependencies]
shaman = "0.1.0"
rayon = "0.9.0"               # Simple work-stealing parallelism for Rust
